[package]
name = "utils"
version = "0.1.0"
authors = ["Maksim Kurnikov <maxim.kurnikov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.30"
log = "0.4"
walkdir = "2.3.1"
ra_vfs = "0.6.1"
