[package]
name = "move-executor"
version = "0.1.0"
authors = ["Maksim Kurnikov <maxim.kurnikov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
serde = "1.0.106"
serde_json = "1.0.52"
clap = "2.33.1"

libra-types = { git = "https://github.com/dfinance/libra.git", branch = "15.09.2020" }

dialects = { path = "../dialects" }
lang = { path = "../lang" }
utils = { path = "../utils" }