[package]
name = "lang"
version = "0.1.0"
authors = [
    "Alex Koz. <alexanderkozlovskii@wings.ai>",
    "Dm. Yakushev <dmitryyakushev@wings.ai>",
    "Maxim Kurnikov <maximkurnikov@wings.ai>"
]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libra = { package = "dfibra", git = "https://github.com/dfinance/libra.git", branch = "15.09.2020" }
move-core-types = { git = "https://github.com/dfinance/libra.git", branch = "15.09.2020" }
move-lang = { git = "https://github.com/dfinance/libra.git", branch = "15.09.2020" }

log = "0.4"
env_logger = "0.7.1"
anyhow = "1.0.27"
rand = "0.7.3"
hex = "0.4.2"
itertools = "0.9.0"
dialects = { path = "../dialects" }
utils = { path = "../utils" }

