[package]
name = "net"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = { version = "1.0", default-features = false }
http = "0.2"
serde = { version = "1.0.125", features = ["derive", "rc"] }
serde_json = "1.0"
log = "0.4"
hex = "0.4"
reqwest = { version = "0.10", features = ["blocking", "json"] }
bcs = "0.1.2"

lang = { path = "../lang" }

move-core-types = { git = "https://github.com/pontem-network/diem.git", branch = "release-1.2.0-v2" }
move-vm-runtime = { git = "https://github.com/pontem-network/diem.git", branch = "release-1.2.0-v2", features = ["debug_module"] }
vm = { git = "https://github.com/pontem-network/diem.git", branch = "release-1.2.0-v2" }

# ps:
[dependencies.substrate-api-client]
git = "https://github.com/scs/substrate-api-client.git"
rev = "62afbac0be1928681d8c70565fa0cc39a92cf4c8"
[dependencies.keyring]
version = '2.0.0'
package = "sp-keyring"
[dependencies.sp-core]
version = '2.0.0'
